from typing import Final

# fmt: off
GROUP_MANAGER_DESC: Final[str] = "Edit settings related to quiz bot managers."
GROUP_QUIZ_DESC: Final[str] = "Create, delete, and list quizzes."
GROUP_EDIT_DESC: Final[str] = "Edit settings for individual quizzes, such as the number of required correct questions."

CMD_MANAGER_ADD_DESC: Final[str] = "Add user as a new bot manager."
CMD_MANAGER_ADD_MANAGER: Final[str] = "Guild member to add as a new bot manager."
CMD_MANAGER_REMOVE_DESC: Final[str] = "Remove an existing bot manager."
CMD_MANAGER_REMOVE_MANAGER: Final[str] = "Guild member to revoke bot manager permissions from."
CMD_MANAGER_CHECK_DESC: Final[str] = "Check if a guild member is an existing bot manager."
CMD_MANAGER_CHECK_USER: Final[str] = "Guild member to check."
CMD_MANAGER_LIST_DESC: Final[str] = "List all current bot managers."
CMD_QUIZ_ADD_DESC: Final[str] = "Add a new quiz type."
CMD_QUIZ_ADD_QUIZ_TYPE: Final[str] = "The slug/name of the new quiz. This will be used both by bot managers and students."
CMD_QUIZ_ADD_QUIZ_LENGTH: Final[str] = "The number of questions in each quiz."
CMD_QUIZ_ADD_MIN_CORRECT: Final[str] = "The minimum number of correctly answered questions to pass this quiz."
CMD_QUIZ_ADD_REQUIRED_ROLE: Final[str] = "The role required to start this quiz (such as an 'enrolled' role)."
CMD_QUIZ_ADD_PASSING_ROLE_ONE: Final[str] = "The role granted to a user if they pass the quiz."
CMD_QUIZ_ADD_PASSING_ROLE_TWO: Final[str] = "[Optional] A secondary role granted to a user if they pass the quiz."
CMD_QUIZ_ADD_NON_PASSING_ROLE: Final[str] = "The role granted to a user if they **do not** pass the quiz."
CMD_QUIZ_ADD_PASSED_TEXT: Final[str] = "[Optional] The text displayed to a user at the end of their quiz if they pass."
CMD_QUIZ_ADD_NOT_PASSED_TEXT: Final[str] = "[Optional] The text displayed to a user at the end of their quiz if they **do not** pass."
CMD_QUIZ_REMOVE_DESC: Final[str] = "Remove an existing quiz type. THIS WILL DELETE ALL SETTINGS AND QUESTIOSN ASSOCIATED WITH THIS QUIZ."
CMD_QUIZ_REMOVE_QUIZ_TYPE: Final[str] = "The slug/name of the quiz to remove."
CMD_QUIZ_LIST_DESC: Final[str] = "List all existing quiz types."
CMD_QUIZ_GET_DESC: Final[str] = "Get the settings for an existing quiz type."
CMD_QUIZ_GET_QUIZ_TYPE: Final[str] = "The slug/name of the quiz to get settings for."
CMD_QUIZ_EDIT_QUIZ_LENGTH_DESC: Final[str] = "Edit how many questions appear on a quiz."
CMD_QUIZ_EDIT_QUIZ_LENGTH_QUIZ_TYPE: Final[str] = "The slug/name of the quiz to edit."
CMD_QUIZ_EDIT_QUIZ_LENGTH_QUIZ_LENGTH: Final[str] = "The number of questions to present to a user for this test."
CMD_QUIZ_EDIT_MIN_SCORE_DESC: Final[str] = "Edit what the minimum amount of correct questions is to pass."
CMD_QUIZ_EDIT_MIN_SCORE_QUIZ_TYPE: Final[str] = "The slug/name of the quiz to edit."
CMD_QUIZ_EDIT_MIN_SCORE_MIN_CORRECT: Final[str] = "The number of questions a user needs to get correct to pass this quiz."
